const EMAIL_REGEX = /^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+.[a-zA-Z0-9]+$/;

//Authentication Action constants
const LOGOUT_ACTION = "LOGOUT";
const LOGIN_ACTION = "LOGIN";
const SIGN_UP_ACTION = "SIGN_UP";
const USER_ACTION = "USER";

//User Data Action Constants
const UPDATE_NOTES_ACTION = "UPDATE_NOTES";
const UPDATE_ARCHIVES_ACTION = "UPDATE_ARCHIVES";
const ADD_TO_TRASH_ACTION = "ADD_TO_TRASH";
const ADD_TO_ARCHIVES_ACTION = "ADD_TO_ARCHIVES";
const RECOVER_FROM_ARCHIVES_ACTION = "RECOVER_FROM_ARCHIVES";
const RECOVER_FROM_TRASH_ACTION = "RECOVER_FROM_TRASH";
const UPDATE_TRASH_ACTION = "UPDATE_TRASH";
const RESET_ACTION = "RESET";

//UseAuthForm hook action constants
const FULL_NAME_ACTION = "FULL_NAME";
const EMAIL_ACTION = "EMAIL";
const PASSWORD_ACTION = "PASSWORD";
const CONFIRM_PASSWORD_ACTION = "CONFIRM_PASSWORD_ACTION";
const DISPLAY_ACTION = "DISPLAY";

//NotePage Reducer actions
const TITLE_ACTION = "TITLE";
const TEXT_ACTION = "TEXT";
const NOTE_ACTION = "NOTE";
const SAVE_TOGGLE_ACTION = "SAVE_TOGGLE";
const SAVE_LOADING_ACTION = "SAVE_LOADING";

//Note reducer actions
const ADD_LABEL_ACTION = "ADD_LABEL";
const REMOVE_LABEL_ACTION = "REMOVE_LABEL";
const NOTE_COLOR_ACTION = "NOTE_COLOR";
const PINNED_ACTION = "PINNED";
const LABEL_TOGGLE_ACTION = "LABEL_TOGGLE";

export {
  EMAIL_REGEX,
  LOGOUT_ACTION,
  LOGIN_ACTION,
  SIGN_UP_ACTION,
  USER_ACTION,
  UPDATE_NOTES_ACTION,
  UPDATE_ARCHIVES_ACTION,
  ADD_TO_TRASH_ACTION,
  ADD_TO_ARCHIVES_ACTION,
  RECOVER_FROM_ARCHIVES_ACTION,
  RECOVER_FROM_TRASH_ACTION,
  UPDATE_TRASH_ACTION,
  RESET_ACTION,
  FULL_NAME_ACTION,
  EMAIL_ACTION,
  PASSWORD_ACTION,
  CONFIRM_PASSWORD_ACTION,
  DISPLAY_ACTION,
  TITLE_ACTION,
  TEXT_ACTION,
  NOTE_ACTION,
  SAVE_TOGGLE_ACTION,
  SAVE_LOADING_ACTION,
  ADD_LABEL_ACTION,
  REMOVE_LABEL_ACTION,
  NOTE_COLOR_ACTION,
  PINNED_ACTION,
  LABEL_TOGGLE_ACTION,
};
